### ISSUE TITLE
integration-test plugin uses deprecated Gradle methods

### ISSUE THREAD

**Issue by jenarros-ct** [ewerk/gradle-plugins#100]
It seems that the integration plugin uses now deprecated methods. Running with Gradle 4.8 I get the following warning message:
```
$ gradle clean build --warning-mode=all

> Configure project :
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
```

**Comment by holgerstolzenberg** [comment]
Currently it is very hard to keep the pace with the Gradle release cycle. The plugins are currently developed against Gradle `4.3.1` so the deprecation warnings with Gradle `4.8` are legitime.

I am not quite sure how to deal with this yet. There are some other internal changes that need to be made to the plugins in order to comply to the latest Gradle stuff.

I think I´ll prefer to update all the plugins completely once Gradle 5 is out and give them a new major version. Can you live with the deprecation warnings at the moment?

@griffio What do you think about that.

**Comment by jenarros-ct** [comment]
I understand, we can live with it for now. Thanks!

**Comment by griffio** [comment]
@holgerstolzenberg 
Yes - Gradle seems to release a major point release every month - so it won't be long 🔢 

In this specific case it's possible to update the deprecation, however it would break compatibility with gradle version < 4
See https://github.com/ewerk/gradle-plugins/pull/101

The Gradle deprecated api changes can be seen in each version - for example https://docs.gradle.org/4.0/release-notes.html#deprecations

**Comment by holgerstolzenberg** [comment]
The MR provided by @griffio has been merged to MASTER. 

@jenarros-ct: Could you please give the snapshot version a try before I release the new Version?

**Comment by jenarros-ct** [comment]
I have tried the version from master and the warning is gone. Thanks a lot!

**Comment by holgerstolzenberg** [comment]
Also see #116.
