### ISSUE TITLE
Annotation processor plugin sourceSets

### ISSUE THREAD

**Issue by L3K0V** [ewerk/gradle-plugins#26]
Hi,
I have compiler project and library module in project.
1. Compiler - all annotation processing stuff
2. Project - Annotated classes and other stuff
3. Library - Annotations and utils

AnnotationProcessing plugin generates new classes in generated source set for all annotated classes in Project. So in Project I have main and generated source sets. **All generated classes depends on Library project.** 

In `build/classes` folder can be found only main source set with all classes (including generated)
When I try to execute explicitly `compileAnnotationProcessorJava` ,generated classes cannot resolve their dependencies from Library project.

Imagine if we have same packages in main and generated sourceSet and java files with same names.

```
src/generated/com/package1/blabla.java (generated after annotation processing)
src/main/com/package1/blabla.java (annotated)
```

I cannot include my generated package with all classes from generated source set and in same time to exclude package with annotated classes from main source set.

My not working fat jar task is:

```
task frameworkJar(type: Jar) {
    baseName = project.name
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from (sourceSets.main.output) {
        exclude 'com/package1/subpackage1/devices/**'
    }
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}
```

also if I add 

```
  from (sourceSets.generated.output) {
        include 'com/package1/subpackage1/devices/**'
    }
```

nothing happened.

**Comment by L3K0V** [comment]
#### Another approach: 
I try to define new sourceSet

```
sourceSets {
    generated
}
```

in dependencies I add

```
compileGenerated project(:library)
```

then again not working jar file looks like:

```
task frameworkJar(type: Jar) {
    baseName = project.name
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    exclude 'com/package1/subpackage1/devices/**'
    with jar

    from sourceSets.generated.output
}
```

and devices package is excluded from jar, generated one must be added but is missing...

**Comment by griffio** [comment]
Hi @L3K0V, 

To try and get a better understanding, the issue here is with creating a JAR - "I cannot include my generated package with all classes from generated source set and in same time to exclude package with annotated classes from main source set"?

Agree, the "generated.java" and "main.java" sources will compile to "sourceSets.main.output" under (build/classes/) and will get archived under "lib" using the default Jar Task.

You want to exclude your "annotated" classes from the JAR as only the generated classes are used and some additional classes as well?

I can suggest that you could prefix (G_) your processor generated classes, if they mirror the same package, to make it easier to include them using a pattern.

The Jar task would be like this using includes only - The annotated classes are not included.

~~~
  tasks.withType(Jar) {
    from sourceSets.main.output
    include 'com/package1/**/G_**'
    include 'com/package1/other/**'
  }
~~~

Regards,

@griffio

**Comment by L3K0V** [comment]
Hi @griffio, 

Thanks for the answer. I workaround the problem by separate annotated classes and generated in packages with different names. Your suggestion also will do the work, but...

I notice that you include all generated files in main source set.The question is if there is way to select annotationProcessor's sourceset with `from...` in jar task for example?

And second question - is there way to set dependencies to annotationProcessor sourceset?

For example:
```
dependencies {
compileAnnotationProcessor project(':someotherproject')
}
```
 
Also if such separation is bad idea can you explain me why?

**Comment by griffio** [comment]
Hi @L3K0V,

1. The “generated” SourceSet is compiled to “build/main/” because the standard tasks use that class-path by default. e.g JAR task.

The “classes/build/generated” output class-path does not exist and “from sourceSets.generated.output” wouldn’t provide any files to the JAR task. It is possible in Gradle to have separate class-paths (for main and generated SourceSets) but the JAR task then has to be extended to include it.

2. The annotation processor plugin has an “annotationProcessor” SourceSet, “annotationProcessor” Configuration where dependencies are set and a task “compileAnnotationProcessor”.
This would add additional dependencies to the "compileAnnotationProcessor" task class-path.

~~~
dependencies {
    annotationProcessor project(':someotherproject')
 }
~~~

If its code from your local project then it should be ok to add project dependencies.

Typically a plugin solves a basic scenario that replaces boiler-plate script.
For complete control and customisation then a build script is best.

We can close this issue for now and you can investigate further with your approaches and raise another issue if required.

Regards,

@griffio
