### ISSUE TITLE
If you set autoValueSourcesDir to be the source dir, you lose all of your source

### ISSUE THREAD

**Issue by nedtwigg** [ewerk/gradle-plugins#27]
If you do this:

```groovy
autoValue {
  autoValueSourcesDir = <SOURCE DIRECTORY>
}
```

Then SOURCE DIRECTORY will be deleted.  Maybe I should have seen this coming, but I definitely just deleted all my source code.

Eclipse "restore from history" FTW!

**Comment by griffio** [comment]
Hi @nedtwigg - Glad you got it back.

Yes  - it is possible to generate the source code into your "src/main/java" but then if you use "clean" it will wipe out the whole file tree.

Were you intentionally trying to mix the main src and generated src together?
I haven't used eclipse - does it support additional src directories?

Regards, @griffio

**Comment by nedtwigg** [comment]
> Were you intentionally trying to mix the main src and generated src together?

Yup.  I don't do that anymore, what with my source code being valuable to me ;-)

> I haven't used Eclipse - does it support additional src directories?

It does.  I think it would be perfectly reasonable to say "we don't support setting the generated directory to be the source directory", and throw a build error if the user tries to do it.  It would also be reasonable to only clean "AutoValue_" classes.  But the current state makes it very easy to accidentally shoot one's face off.

**Comment by holgerstolzenberg** [comment]
I think it difficult to just say we throw an exception in that case. I am on your side, but there may be someone else who really needs it this way!? At least everything can be resolved by configuration.

**Comment by griffio** [comment]
@holgerstolzenberg 

Raising an exception, the check would have to ensure that "autoValueSourcesDir" is not pointing to *any* other existing source folder and is probably too pessimistic compared to the alternative.

If I can look into using a *soft delete* in the clean task that removes "AutoValue_" source files from the "autoValueSourcesDir" tree and only deletes the directory if its empty.

This covers the usage where a user wants to generate into an existing source folder.

I can/need to investigate this since the plugin creates ""autoValueSourcesDir" and may cause a problem with gradle internals if the directory already exists. 

Of course, the other plugins are doing the same *hard delete". What the plugin tasks perform should be documented further (directories created, deleted etc).

Regards,

@griffio

**Comment by nedtwigg** [comment]
I'm not generating the code into my source directory any more.  It's not a big deal to me to have a separate folder, and I'm not gonna risk combining them again, regardless of where this issue goes, so I'm not super invested.

> but there may be someone else who really needs it this way!?

If there is, then they can raise an issue.  I don't think anyone wants to delete their source code when they do `clean build`.  On the bright side, the build is really really fast after the clean.  The current behvaior is **super** dangerous, if the user really intends to delete their source code everytime they run `clean`, they should at least have to set `overrideSafety = true` to confirm that they realize the danger.

> the check would have to ensure that "autoValueSourcesDir" is not pointing to any other existing source folder and is probably too pessimistic compared to the alternative

If you just check "does autoValueSourcesDir.equals(sourceSets['main'].srcDir)", then you'll catch most projects.  It would have caught mine.

I guess plenty of people have managed to use it without shooting themselves in the face like I did.  But if 100 more people use this in the future, maybe 10 of them will shoot themselves.  I think adding a simple check for the most common failure wil save 9 of those 10.

**Comment by griffio** [comment]
@nedtwigg Ok thanks, agreed we shouldn't blindly delete the main source folder!

@holgerstolzenberg After investigating, the auto-value plugin, https://github.com/ewerk/gradle-plugins/blob/master/plugins/auto-value-plugin/src/main/groovy/com/ewerk/gradle/plugins/AutoValuePlugin.groovy#L70, When source/generated source is co-located it can't an existing "generated" file - internal java annotation processor state is violated since it sees the generated source on the compiler source path!

I can certainly look into adding a check as @nedtwigg suggests.

Regards,

griffio

**Comment by holgerstolzenberg** [comment]
The PR has been merged and released. Plugin in version 1.0.6 available at the portal.

@griffio Thanks for your fast response and help. Always a pleasure.
