### ISSUE TITLE
Extract sample-application to separate project (do not interfere release any more)

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#43]
@griffio What do you think?

**Comment by griffio** [comment]
Yes, makes it easier.

Rather than just moving sample-application to a new repo, could suggest that any new "gradle_plugins_sample_applications" repo is just a top level folder that contains the current sample-application and will allow me to add some more sample projects e.g:

~~~
/gradle_plugins_sample_applications
     /android_application
     /multi-module_application
     /sample-application
     /springdata_application
~~~

Not talking about adding git-submodules though, just sub-directories with build gradle file.

**Comment by holgerstolzenberg** [comment]
Sounds reasonable.

**Comment by holgerstolzenberg** [comment]
@griffio Can you provide a PR so that I can focus on the JDK-8 upgrade.
