### ISSUE TITLE
Recent Querydsl plugins not published to JCenter

### ISSUE THREAD

**Issue by emersonf** [ewerk/gradle-plugins#44]
The [list of available versions](https://bintray.com/bintray/jcenter/querydsl-plugin/view) shows the latest version as 1.0.3.

**Comment by holgerstolzenberg** [comment]
Gradleware recently changed there publishing mechanism. The plugins have no need to be on Bintray in order to be available through the plugin portal, which is becoming the preferred way.

Please get the latest version as described here:

https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.querydsl

**Comment by emersonf** [comment]
Thanks for the quick answer. 

FYI the [plugin README](https://github.com/ewerk/gradle-plugins/tree/master/plugins/querydsl-plugin) still contains JCenter information at version 1.0.6.

**Comment by holgerstolzenberg** [comment]
Removed outdated documentation
