### ISSUE TITLE
Can this plugin be modified to support scala classes?

### ISSUE THREAD

**Issue by TheKojuEffect** [ewerk/gradle-plugins#55]
Would it be possible for this plugin to support processing Entity classes in scala and generating scala meta models?

**Comment by griffio** [comment]
Hey there @TheKojuEffect, based on my understanding, maybe you are talking about using [querydsl scala support](http://www.querydsl.com/static/querydsl/4.1.0/reference/html_single/#scala)?

We would have to add dual support for https://docs.gradle.org/current/userguide/scala_plugin.html.

Although, I think it's outside the scope for the plugins maintained here as they specifically focus on Gradle with the Java compiler plugin and annotation processor tool support.

Do you want to provide more background around your issue? Otherwise can you close it now as there is not an immediate solution - at best we would have to create a new plugin.

**Comment by TheKojuEffect** [comment]
Hey @griffio, thank you for your reply. Yes, I was talking about querydsl scala support. I was looking if we can extend or use this plugin to generate querydsl meta model classes in scala from entity classes written in scala?

Thanks!

**Comment by griffio** [comment]
Hi @TheKojuEffect,

Looking into it - http://www.querydsl.com/static/querydsl/4.1.3/reference/html_single/#scala, since there is no concept of an automatic compiler processor, the Scala code generation is performed by setting up the ScalaMetaDataSerializer for SQL backends or with JPA and other backends by creating the query classes manually or with the $alias for collections. 

An example setup for JPA would be this: https://github.com/querydsl/querydsl/blob/master/querydsl-scala/src/test/scala/com/querydsl/scala/GenericExporterJPATest.scala

Sorry it can't be supported here!

Regards, 

@griffio

**Comment by TheKojuEffect** [comment]
Hey @griffio Thank You, I will go ahead and close this issue.
