### ISSUE TITLE
Querydsl plugin doesn't work with compileGroovy

### ISSUE THREAD

**Issue by tadaskay** [ewerk/gradle-plugins#73]
In a mixed Java-groovy project, I am joint compiling with groovy using the following configuration:

```gradle
    apply plugin: 'java'
    apply plugin: 'groovy'

    sourceSets.main.java.srcDirs = []
    sourceSets.main.groovy.srcDirs = ['src/main/java', 'src/main/groovy']
```

This plugin simply [adds generated sources](https://github.com/ewerk/gradle-plugins/blob/master/querydsl-plugin/src/main/groovy/com/ewerk/gradle/plugins/QuerydslPlugin.groovy#L81) to `compileJava` source without any checks:

```groovy
  private void registerSourceAtCompileJava(Project project, File querydslSourcesDir) {
    project.compileJava {
      source querydslSourcesDir
    }
  }
```

As you can already spot, the compilation fails, because java sourceset now only contains the querydsl classes (everything else is under groovyCompile).

Update: somehow missed that `class QuerydslCompile extends JavaCompile`, so indeed only `JavaCompile` is supported 😉

**Comment by holgerstolzenberg** [comment]
Hm. It seems like supporting Groovy is a general wish out there, as we have similar issues open for other plugins. The original intention was to provide plugins that support our Java development team. We are not using Groovy by now.
So here we are at some kind of split point. I am not quite sure if we should support Groovy. I can see the next requests coming up because we need to support Scala or Kotlin.
If we decide to support Groovy, we need to think about how to do it first. 
The options I see so far:
* simple conditional language switch
* some kind of base plugin + dedicated plugins foreach lang (querydsl-java, querydsl-groovy, …)

@griffio What do you think?
@tadaskay Your opinion?

**Comment by tadaskay** [comment]
Fair enough.

Most of the plugins we're using work with Java/Groovy transparently (after all, the mixed code is compiled to the very same classes and put into JARs just like Java), and Gradle API works equally well with most of JVM languages.

What about detecting compile tasks or attaching to all of them? Querydsl configuration is very similar if not identical to Java's (except for `GroovyCompile` being used instead of `JavaCompile` - I guess that would also be the case for the other languages).

Since I have a working setup with Querydsl + Java + Groovy (currently implemented as a Gradle buildscript, but I would gladly replace it with a single plugin call), I could probably come up with a proposal PR.

WDYT?

**Comment by holgerstolzenberg** [comment]
Sounds good. PRs always appreciated. Would like to welcome more contributors to the family 😎

**Comment by holgerstolzenberg** [comment]
@tadaskay You should also have a look at #71.

**Comment by holgerstolzenberg** [comment]
@tadaskay Any news on this one?

**Comment by holgerstolzenberg** [comment]
Groovy will not be supported.
