### ISSUE TITLE
querydsl plugin conflicts with IntelliJ internal platform test runner 

### ISSUE THREAD

**Issue by gclayburg** [ewerk/gradle-plugins#93]
I have a simple spring boot project using gradle.  It has one test that basically just verifies it can read properties from application.properties file.  Things work fine running this test under gradle or under the internal IntelliJ IDEA test runner.

However, if I enable this line in buld.gradle

```
plugins{
	id "com.ewerk.gradle.plugins.querydsl" version "1.0.9"
}
```

then IntelliJ IDEA test runner fails when running the test.  It seems that for some reason the classpath used by the test runner now has the wrong order.

Here is an abbreviated classpath used:

`/home/gclaybur/dev/gradleintellij/out/test/classes:/home/gclaybur/dev/gradleintellij/out/production/classes:/home/gclaybur/dev/gradleintellij/out/production/resources:/home/gclaybur/dev/gradleintellij/out/test/resources`

You can see that the test resources are now listed **after** the production resources directory.  For my test to work, the test resources must be listed first.

Any idea what is happening here?  I can share the entire project if you like.  Its quite easy to verify.

**Comment by gclayburg** [comment]
Ok, for anyone else running into this, I found an IntelliJ setting to workaround this issue.  When this plugin is used, you need to check the "Delegate IDE build/run actions to gradle".  Without this, the IntelliJ 
project model gets confused when also using the "Platform Test Runner".

![delegate-ide-build-run-actions-to-gradle](https://user-images.githubusercontent.com/1435496/36069183-02a664ee-0ea2-11e8-873c-1a5e4965d9cb.png)

**Comment by gclayburg** [comment]
Ok, I shared a project that demonstrates this issue here:
https://github.com/gclayburg/querydsl-plugin-intellij-fail

To see the issue, do this:
1. clone the project
2. import the project into intellij.
3. try running the tests - they should fail
4. comment out the import of the querydsl gradle plugin in build.gradle and re-run the tests.

**Comment by holgerstolzenberg** [comment]
I tried your sample and I do not think that this is an issue with the `querydsl-plugin` at all! I think the problem is that you have an `application.properties` file under `src/main/resources` and under `src/test/resources` which is problematic in terms of Java classpath loading. Your sample works from command line but not from IDE. There is no guarantee the IDE and Gradle collect resources from the classpath in the same way or same sequence. From the command line the correct file wins, from the IDE not. Is is generally a bad pattern. You need to rename your test application properties and use profiles or configuration overrides via system-, java- or env-properties. This is more a Spring Boot specific thing.

**Comment by gclayburg** [comment]
> I think the problem is that you have an application.properties file under src/main/resources and under src/test/resources which is problematic in terms of Java classpath loading. Your sample works from command line but not from IDE.

As I recall, this is only true when querydsl plugin is used.  Remember, the sample also works from both command line and IDE when the plugin is not enabled.  I didn't look at the querydsl source code in great detail, but it looks like there is some sourceset manipulation going on. Maybe that introduces the subtle issue you identified?

**Comment by holgerstolzenberg** [comment]
I didn´t look at the source code for a long time either 😉

The `sourceSet` manipulation does change the behaviour how the final class path works. What the plugin generally does is adding `src/querydsl/java` to the classpath.

Still it is no good to have multiple resources with the same name on the classpath. You will have no guarantee that the correct one will be picked up by the classloader.

**Comment by gclayburg** [comment]
Right, I wish I had the time to generate a PR for this but I'm just swamped at the moment.  I am ok with the workaround I mentioned some time ago.  

> Still it is no good to have multiple resources with the same name on the classpath. You will have no guarantee that the correct one will be picked up by the classloader.

Not to be too nit-picky, but this statement is true with regards to the Java classpath in general, but in the case of the maven and gradle standard directory layout, there are assurances as to which `application.properties` will be loaded.  During the test phase, `src/test/resources` will always occur before `src/main/resources` in the classpath .  I've used this for fact years and it works great.  If this were not the case, the `src/test/resources` would not be nearly as useful.  It is quite common to need to override settings just for testing.

**Comment by afganhalbana** [comment]
Hi @gclayburg thanks for saving my ass !! I've been strugling this for a day, your workaround also work for me. In my case Intellij 2018.1 CE can't recognized the QClass which is already generated because somehow the QClass is not included in build path even tho i already mark it as a source directory. That happens because i have some codes that need to access to generated class directly. 
So after adding the source path in my gradle with this code 
``` 
sourceSets {
    main {
        java {
            srcDir "src/main/generated"
        }
    }
}
```
and your workaround to check the "Delegate IDE build/run actions to gradle" in the settings, everything works fine now, hope this help anyone who have the same problem.

**Comment by gclayburg** [comment]
Interesting that you mention that, @afganhalbana .  I was just looking at this issue again yesterday.  I have re-organized my project and this workaround no longer works for me.  I strongly suspect that this gradle plugin manipulates the test classpath in subtle ways that cause the IntelliJ internal test runner to use an incorrect classpath.
